# Assignment 2
For this assignment you'll be looking at 2017 data on immunizations from the CDC. Your datafile for this assignment is in [assets/NISPUF17.csv](assets/NISPUF17.csv). A data users guide for this, which you'll need to map the variables in the data to the questions being asked, is available at [assets/NIS-PUF17-DUG.pdf](assets/NIS-PUF17-DUG.pdf). **Note: you may have to go to your Jupyter tree (click on the Coursera image) and navigate to the assignment 2 assets folder to see this PDF file).**

In [107]:
import pandas as pd

df=pd.read_csv("assets/NISPUF17.csv")

Index(['Unnamed: 0', 'SEQNUMC', 'SEQNUMHH', 'PDAT', 'PROVWT_D', 'RDDWT_D',
       'STRATUM', 'YEAR', 'AGECPOXR', 'HAD_CPOX',
       ...
       'XVRCTY2', 'XVRCTY3', 'XVRCTY4', 'XVRCTY5', 'XVRCTY6', 'XVRCTY7',
       'XVRCTY8', 'XVRCTY9', 'INS_STAT2_I', 'INS_BREAK_I'],
      dtype='object', length=454)

## Question 1
Write a function called `proportion_of_education` which returns the proportion of children in the dataset who had a mother with the education levels equal to less than high school (<12), high school (12), more than high school but not a college graduate (>12) and college degree.

*This function should return a dictionary in the form of (use the correct numbers, do not round numbers):* 
```
    {"less than high school":0.2,
    "high school":0.4,
    "more than high school but not college":0.2,
    "college":0.2}
```

In [120]:
def proportion_of_education():
    les=df[(df['EDUC1']==1)]
    les1=df[(df['EDUC1']==2)] 
    les2=df[(df['EDUC1']==3)]
    les3=df[(df['EDUC1']==4)]
    total=len(df['EDUC1'])
    a=les['EDUC1'].count()/total
    b=les1['EDUC1'].count()/total
    c=les2['EDUC1'].count()/total
    d=les3['EDUC1'].count()/total
    dicc={"less than high school":a,
    "high school":b,
    "more than high school but not college":c,
    "college":d}
    return dicc
    #raise NotImplementedError()

In [121]:
proportion_of_education()

{'less than high school': 0.10202002459160373,
 'high school': 0.172352011241876,
 'more than high school but not college': 0.24588090637625154,
 'college': 0.47974705779026877}

In [122]:
assert type(proportion_of_education())==type({}), "You must return a dictionary."
assert len(proportion_of_education()) == 4, "You have not returned a dictionary with four items in it."
assert "less than high school" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "high school" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "more than high school but not college" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "college" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."

## Question 2

Let's explore the relationship between being fed breastmilk as a child and getting a seasonal influenza vaccine from a healthcare provider. Return a tuple of the average number of influenza vaccines for those children we know received breastmilk as a child and those who know did not.

*This function should return a tuple in the form (use the correct numbers:*
```
(2.5, 0.1)
```

In [145]:
def average_influenza_doses():
    milk=df[(df['CBF_01']==1)] 
    r=milk['P_NUMFLU'].dropna().mean()
    milk1=df[(df['CBF_01']==2)]
    r1=milk1['P_NUMFLU'].dropna().mean()
    tupla=(r,r1)
    return tupla
    #raise NotImplementedError()

In [146]:
assert len(average_influenza_doses())==2, "Return two values in a tuple, the first for yes and the second for no."

## Question 3
It would be interesting to see if there is any evidence of a link between vaccine effectiveness and sex of the child. Calculate the ratio of the number of children who contracted chickenpox but were vaccinated against it (at least one varicella dose) versus those who were vaccinated but did not contract chicken pox. Return results by sex. 

*This function should return a dictionary in the form of (use the correct numbers):* 
```
    {"male":0.2,
    "female":0.4}
```

Note: To aid in verification, the `chickenpox_by_sex()['female']` value the autograder is looking for starts with the digits `0.0077`.

In [173]:
DFM=df[(df['SEX']==1)]
DFF=df[(df['SEX']==2)]

,Unnamed: 0,SEQNUMC,SEQNUMHH,PDAT,PROVWT_D,RDDWT_D,STRATUM,YEAR,AGECPOXR,HAD_CPOX,...,XVRCTY2,XVRCTY3,XVRCTY4,XVRCTY5,XVRCTY6,XVRCTY7,XVRCTY8,XVRCTY9,INS_STAT2_I,INS_BREAK_I
0,1,128521,12852,2,NaN,235.916956,1031,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,10741,1074,2,NaN,957.353840,1068,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,207941,20794,2,NaN,35.995367,1019,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,161121,16112,1,978.042448,718.616990,1016,2017,3.0,1,...,,,NaN,NaN,NaN,NaN,NaN,NaN,4.0,4.0
9,10,143401,14340,2,NaN,1536.859533,1068,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,128211,12821,1,335.398714,198.123294,1057,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
12,13,137041,13704,1,82.582116,45.544717,1051,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
13,14,46531,4653,2,NaN,1116.347858,1025,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,87781,8778,2,NaN,168.413904,1044,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16,41081,4108,2,NaN,685.693874,1036,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,188611,18861,1,345.352030,196.111859,1057,2017,NaN,2,...,VO,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
17,18,461,46,2,NaN,90.028928,1017,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19,462,46,2,NaN,90.028928,1017,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20,136171,13617,1,223.451930,136.912758,1059,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
21,22,238751,23875,1,270.449794,134.563612,1058,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2.0
23,24,195021,19502,2,NaN,256.041114,1002,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,28,233941,23394,1,340.470079,253.165839,1002,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
29,30,187771,18777,1,91.660790,49.045451,1108,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
30,31,85841,8584,1,369.278774,246.849202,1040,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
34,35,133391,13339,1,347.907710,273.831260,1002,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
36,37,51331,5133,1,30.587606,17.107666,1004,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
39,40,188341,18834,1,1710.901115,600.056340,1040,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0
41,42,7141,714,1,43.938347,24.520784,1004,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
42,43,205551,20555,2,NaN,96.913664,1056,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,44,265921,26592,1,31.857456,23.878294,1063,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0
46,47,6211,621,1,305.925227,242.761678,1001,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0
49,50,4791,479,1,715.026025,422.674132,1040,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
51,52,79851,7985,2,NaN,635.788607,1011,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,53,125651,12565,2,NaN,209.826312,1066,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,54,23321,2332,1,72.517239,46.389810,1062,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28401,28402,187051,18705,2,NaN,39.592378,2074,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28402,28403,221901,22190,1,151.066296,65.345122,2064,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
28403,28404,77241,7724,1,398.175303,166.040534,2051,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
28404,28405,177661,17766,1,128.133719,105.089644,2020,2017,1.0,1,...,,,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0
28405,28406,184651,18465,2,NaN,78.114044,1047,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28406,28407,20531,2053,1,125.160499,74.218547,1049,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0
28408,28409,254011,25401,1,20.093784,14.096999,1061,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
28409,28410,541,54,1,383.611545,113.584661,1047,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0
28412,28413,115021,11502,1,48.969974,31.192700,1049,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0
28415,28416,144771,14477,1,187.395413,124.857840,2052,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0
28417,28418,52321,5232,2,NaN,77.675462,2052,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28418,28419,152191,15219,1,489.266310,238.401302,2052,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0
28420,28421,16241,1624,2,NaN,241.005278,2052,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28421,28422,193351,19335,2,NaN,298.742057,2051,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28423,28424,139981,13998,2,NaN,432.698033,2051,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28425,28426,63801,6380,1,285.273107,141.960064,2052,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
28430,28431,237841,23784,1,537.582011,203.666350,2052,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0
28431,28432,169591,16959,2,NaN,124.857840,2052,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28432,28433,45351,4535,2,NaN,240.801135,2051,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28434,28435,194821,19482,2,NaN,82.187847,2052,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28435,28436,250151,25015,1,99.480351,57.116375,2068,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
28436,28437,79531,7953,1,96.617497,54.463171,2065,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN
28438,28439,126141,12614,1,216.225073,126.221620,2052,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2.0
28439,28440,27411,2741,2,NaN,166.040534,2051,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28443,28444,97321,9732,2,NaN,100.710256,2044,2017,1.0,1,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28447,28448,136841,13684,1,593.426753,337.255316,2031,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
28448,28449,237881,23788,2,NaN,390.466235,2076,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28449,28450,132081,13208,1,166.681363,96.330007,2059,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
28453,28454,122131,12213,2,NaN,33.006992,2013,2017,2.0,1,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28455,28456,154501,15450,2,NaN,56.655283,2062,2017,1.0,1,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [176]:
def chickenpox_by_sex(): 
    MCV=df[(df.P_NUMVRC >=1) & (df.HAD_CPOX == 1) & (df.SEX == 1)]
    MSV=df[(df.P_NUMVRC >=1) & (df.HAD_CPOX == 2) & (df.SEX == 1)]
    FCV=df[(df.P_NUMVRC >=1) & (df.HAD_CPOX == 1) & (df.SEX == 2)]
    FSV=df[(df.P_NUMVRC >=1) & (df.HAD_CPOX == 2) & (df.SEX == 2)]
    M=len(MCV)/len(MSV)
    F=len(FCV)/len(FSV)
    dicc={"male":M,"female":F}
    return dicc
    #raise NotImplementedError()

In [177]:
print(chickenpox_by_sex())

{'male': 0.009675583380762664, 'female': 0.0077918259335489565}

In [158]:
assert len(chickenpox_by_sex())==2, "Return a dictionary with two items, the first for males and the second for females."

## Question 4
A correlation is a statistical relationship between two variables. If we wanted to know if vaccines work, we might look at the correlation between the use of the vaccine and whether it results in prevention of the infection or disease [1]. In this question, you are to see if there is a correlation between having had the chicken pox and the number of chickenpox vaccine doses given (varicella).

Some notes on interpreting the answer. The `had_chickenpox_column` is either `1` (for yes) or `2` (for no), and the `num_chickenpox_vaccine_column` is the number of doses a child has been given of the varicella vaccine. A positive correlation (e.g., `corr > 0`) means that an increase in `had_chickenpox_column` (which means more no’s) would also increase the values of `num_chickenpox_vaccine_column` (which means more doses of vaccine). If there is a negative correlation (e.g., `corr < 0`), it indicates that having had chickenpox is related to an increase in the number of vaccine doses.

Also, `pval` is the probability that we observe a correlation between `had_chickenpox_column` and `num_chickenpox_vaccine_column` which is greater than or equal to a particular value occurred by chance. A small `pval` means that the observed correlation is highly unlikely to occur by chance. In this case, `pval` should be very small (will end in `e-18` indicating a very small number).

[1] This isn’t really the full picture, since we are not looking at when the dose was given. It’s possible that children had chickenpox and then their parents went to get them the vaccine. Does this dataset have the data we would need to investigate the timing of the dose?

In [186]:
dff=df[["HAD_CPOX","P_NUMVRC"]]
dff=dff[dff.HAD_CPOX.isin([1, 2])]
dff=dff[dff.P_NUMVRC.notnull()]
dff

       HAD_CPOX  P_NUMVRC
3             2       1.0
4             2       0.0
6             2       1.0
7             2       0.0
8             1       0.0
...         ...       ...
28446         2       1.0
28447         2       1.0
28449         2       1.0
28452         2       1.0
28454         2       1.0

[15286 rows x 2 columns]

In [187]:
def corr_chickenpox():
    import scipy.stats as stats
    import numpy as np
    import pandas as pd
    
    # this is just an example dataframe
    #df=pd.DataFrame({"had_chickenpox_column":np.random.randint(1,3,size=(100)),
           #        "num_chickenpox_vaccine_column":np.random.randint(0,6,size=(100))})

    # here is some stub code to actually run the correlation
    #corr, pval=stats.pearsonr(df["had_chickenpox_column"],df["num_chickenpox_vaccine_column"])
    
    # just return the correlation
    #return corr
    dff=df[["HAD_CPOX","P_NUMVRC"]] 
    dff=dff[dff.HAD_CPOX.isin([1, 2])] 
    dff=dff[dff.P_NUMVRC.notnull()]
    corr, pval=stats.pearsonr(dff["HAD_CPOX"],dff["P_NUMVRC"])
    return corr
    #raise NotImplementedError()

In [188]:
assert -1<=corr_chickenpox()<=1, "You must return a float number between -1.0 and 1.0."

In [189]:
print(corr_chickenpox())

0.07044873460147986